//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

public class ContactUs
{
    [Key]
    public virtual int ContactUsId
	{
		get;
		set;
	}
    [MaxLength(50,ErrorMessage ="تعداد کاراکترهای نام بیش از حد مجاز است")]
    [Required(ErrorMessage ="نام را وارد کنید")]
    public virtual string ContactUsName
	{
		get;
		set;
	}
    [EmailAddress(ErrorMessage ="ایمیل را بطور صحیح وارد کنید")]
    [Required(ErrorMessage ="ایمیل را وارد کنید")]
    public virtual string ContactUsEmail
	{
		get;
		set;
	}
    [MaxLength(100,ErrorMessage ="تعداد کاراکترهای موضوع بیش از حد مجاز است")]
    [Required(ErrorMessage ="موضوع را وارد کنید")]
    public virtual string ContactUsSubject
	{
		get;
		set;
	}
    [Required(ErrorMessage ="متن را وارد کنید")]
    public virtual string ContactUsText
	{
		get;
		set;
	}
    [Required]
    public bool HasRead { get; set; }

}

