//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

public class Expert
{
    [Key]
    public virtual int ExpertId
	{
		get;
		set;
	}
    [Required(ErrorMessage ="نام را وارد کنید")]
    [MaxLength(50,ErrorMessage ="تعداد کاراکترهای نام بیش از حد مجاز است")]
public virtual string ExpertFullName
	{
		get;
		set;
	}
    [Required(ErrorMessage ="تخصص را وارد کنید")]
    [MaxLength(50, ErrorMessage = "تعداد کاراکترهای تخصص بیش از حد مجاز است")]
    public virtual string ExpertSkill
	{
		get;
		set;
	}
    [MaxLength(150, ErrorMessage = "آدرس غیر مجاز است")]
    [Required(ErrorMessage ="تصویر را انتخاب کنید")]
    public virtual string ExpertImage
    {
        get;
        set;
    }

}

