//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

public class Gallery
{
    [Key]
	public virtual int GalleryPicId
	{
		get;
		set;
	}
    [Required(ErrorMessage ="تصویر را انتخاب کنید")]
    [MaxLength(150)]
    public virtual string GalleryPicAddress
	{
		get;
		set;
	}
    [Required]
    [Column(TypeName ="date")]
    public virtual DateTime GalleryRegisterDate
    {
        get;
        set;
    }

}

