//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Text;

public class NewsPicture
{
    internal class Config:EntityTypeConfiguration<NewsPicture>
    {
        public Config()
        {
            HasRequired(p => p.News).WithMany(p => p.NewsPirctures)
                .HasForeignKey(p=>p.News_NewsId).WillCascadeOnDelete(true);
        }
    }
    [Key]
    public virtual int NewsPicId
	{
		get;
		set;
	}
    [Required(ErrorMessage ="تصویر را وارد کنید")]
    [MaxLength(150,ErrorMessage ="آدرس تصویر غیر مجاز است")]
    public virtual string NewsPicAddress
	{
		get;
		set;
	}
    [ForeignKey("News")]
    public  int News_NewsId
    {
        get;
        set;
    }

    public virtual News News
	{
		get;
		set;
	}
   
    
}

