//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Text;

public class News
{
    [Key]
    public virtual int NewsId
	{
		get;
		set;
	}
    [Required(ErrorMessage ="عنوان خبر را وارد کنید")]
    [MaxLength(50, ErrorMessage = "تعداد کاراکترهای عنوان بیش از حد مجاز است")]
    public virtual string NewsTitle
	{
		get;
		set;
	}
    [Required]
    [Column(TypeName = "date")]
    public virtual DateTime NewsDate
	{
		get;
		set;
	}
    [Required]
    [MaxLength(1000, ErrorMessage = "تعداد کاراکترهای متن خبر بیش از حد مجاز است")]
    public virtual string NewsText
	{
		get;
		set;
	}

	public virtual ICollection<NewsPicture> NewsPirctures
	{
		get;
		set;
	}

    public News()
    {
       NewsPirctures = new HashSet<NewsPicture>();
    }
    

}

