//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

public class Progress
{
    [Key]
    public virtual int ProgressId
	{
		get;
		set;
	}
    [Required(ErrorMessage ="عنوان را وارد کنید")]
    [MaxLength(250,ErrorMessage ="تعداد کاراکترهای عنوان بیش از حد مجاز است")]
	public virtual string ProgressTitle
	{
		get;
		set;
	}
    [Required(ErrorMessage ="متن را وارد کنید")]
	public virtual string ProgressText
	{
		get;
		set;
	}

}

