//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Role
{
	public virtual int RoleId
	{
		get;
		set;
	}

	public virtual string RoleName
	{
		get;
		set;
	}

	public virtual string RoleDesc
	{
		get;
		set;
	}

	public virtual ICollection<User> Users
	{
		get;
		set;
	}

}

