//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

public class Slide
{
    [Key]
	public virtual int SlideId
	{
		get;
		set;
	}
    [Required(ErrorMessage ="عنوان را بطور کامل وارد کنید")]
    [MaxLength(50,ErrorMessage ="کاراکترهای عنوان بیش از حد مجاز است")]
	public virtual string SlideSimpleTitle
	{
		get;
		set;
	}
    [Required(ErrorMessage = "عنوان را بطور کامل وارد کنید")]

    [MaxLength(50, ErrorMessage = "کاراکترهای عنوان بیش از حد مجاز است")]
    public virtual string SlideCssTitle
    {
        get;
        set;
    }
    [MaxLength(500,ErrorMessage ="تعداد کاراکترهای توضیحات بیش از حد مجاز است")]
    public virtual string SlidePicDesc
    {
        get;
        set;
    }
    [MaxLength(150, ErrorMessage = "آدرس عکس نامعتبر است")]
    public virtual string SlidePicAddress
	{
		get;
		set;
	}
    [Required(ErrorMessage ="متن را وارد کنید")]
    public virtual string SlideText
	{
		get;
		set;
	}

}

