//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

public class User
{

    [Key]
    public virtual int UserId
    {
        get;
        set;
    }

    [Required(ErrorMessage ="نام کاربری را وارد کنید")]
    [MaxLength(50, ErrorMessage = "تعداد کاراکترهای نام کاربری بیش از حد مجاز است")]

    public virtual string UserName
    {
        get;
        set;
    }
    [MaxLength(50,ErrorMessage ="تعداد کاراکترهای رمز عبور بیش از حد مجاز است")]
    [Required(ErrorMessage ="رمز عبور را وارد کنید")]
    public virtual string Password
    {
        get;
        set;
    }
    [Required(ErrorMessage ="نام را وارد کنید")]
    [MaxLength(50,ErrorMessage ="تعداد کاراکترهای نام بیش از حد مجاز است")]
    public virtual string UserFirstName
    {
        get;
        set;
    }
    [Required(ErrorMessage = "نام خانوادگی را وارد کنید")]
    [MaxLength(50, ErrorMessage = "تعداد کاراکترهای نام خانوادگی بیش از حد مجاز است")]
    public virtual string UserLastName
    {
        get;
        set;
    }
    [Required]

    [EmailAddress(ErrorMessage = "ایمیل را بطور صحیح وارد کنید")]
    public virtual string UserEmail
    {
        get;
        set;
    }
    [NotMapped]
    public bool remember { get; set; }
    public bool IsActive { get; set; }
    [Required]
    public Guid guid { get; set; }
    public Role role { get; set; }

}

